name: Continuous Integration

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check-formatting:
    runs-on: ubuntu-20.04
    name: Style
    steps:
      - name: Checkout aries-mobile-agent-react-native
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn

      - name: Check formatting
        run: yarn check-format

      - name: Lint
        run: yarn lint
